//
//  StockEntity+CoreDataProperties.swift
//  stocks
//
//  Created by Devon Chan on 2024-08-13.
//
//

import Foundation
import CoreData

// Extension to StockEntity that contains its Core Data properties and additional functionality
// This class was also auto-generated by xcode when creating the Core Data model
extension StockEntity {
    // Generates a fetch request to retrieve StockEntity objects from Core Data.
    @nonobjc public class func fetchRequest() -> NSFetchRequest<StockEntity> {
        return NSFetchRequest<StockEntity>(entityName: "StockEntity")
    }
    // Core Data properties for the StockEntity entity.
    @NSManaged public var exchange: String?
    @NSManaged public var name: String?
    @NSManaged public var sortIndex: Int64
    @NSManaged public var performanceId: String?
    @NSManaged public var price: Double
    @NSManaged public var ticker: String?
    @NSManaged public var rank: String?
    @NSManaged public var stockList: StockListEntity?

}

// Extension that makes StockEntity conform to the Identifiable protocol.
// This is useful for SwiftUI views that require unique identifiers for lists.
extension StockEntity : Identifiable {

}
